main:
  - name: WORLD PIECE COMPUTER
    url: 'https://a.wp.computer'
    weight: 1
  - name: THE UNIVERSAL PIECE
    url: 'https://apx.up.computer'
    weight: 2
  - name: THE UNIVERSAL PIECE COMPUTER
    url: 'https://the.up.computer'
    weight: 3
  - name: THE HUMAN IMPERATIVE
    url: 'https://thehumanimperative.up.computer'
    weight: 4
  - name: $
    url: 'https://time-machine-for-peace.myshopify.com'
    weight: 5

