main:
  - name: WORLD PIECE COMPUTER
    url: 'https://the.wp.computer'
    weight: 1
  - name: UNIVERSAL PEACE
    url: 'https://apx.up.computer'
    weight: 2
  - name: UNIVERSAL PEACE COMPUTER
    url: 'https://the.up.computer'
    weight: 3
  - name: posts
    url: /posts/
    weight: 4
  - name: docs
    url: /docs/
    weight: 5
  - name: $
    url: 'https://time-machine-for-peace.myshopify.com'
    weight: 6

